<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

            $countries =[
                [
                    'id'=>1,
                    'code'=>'AF',
                    'name'=>'Afghanistan',
                    'hasRegion'=>1,
                     'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>2,
                    'code'=>'AL',
                    'name'=>'Albania',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>3,
                    'code'=>'DZ',
                    'name'=>'Algeria',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>4,
                    'code'=>'AS',
                    'name'=>'American Samoa',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>5,
                    'code'=>'AD',
                    'name'=>'Andorra',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>6,
                    'code'=>'AO',
                    'name'=>'Angola',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>7,
                    'code'=>'AI',
                    'name'=>'Anguilla',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>8,
                    'code'=>'AQ',
                    'name'=>'Antarctica',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>9,
                    'code'=>'AG',
                    'name'=>'Antigua And Barbuda',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>10,
                    'code'=>'AR',
                    'name'=>'Argentina',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>11,
                    'code'=>'AM',
                    'name'=>'Armenia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>12,
                    'code'=>'AW',
                    'name'=>'Aruba',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,

                ],
                [
                    'id'=>13,
                    'code'=>'AU',
                    'name'=>'Australia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>14,
                    'code'=>'AT',
                    'name'=>'Austria',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>15,
                    'code'=>'AZ',
                    'name'=>'Azerbaijan',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>16,
                    'code'=>'BS',
                    'name'=>'Bahamas The',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>17,
                    'code'=>'BH',
                    'name'=>'Bahrain',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>18,
                    'code'=>'BD',
                    'name'=>'Bangladesh',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>19,
                    'code'=>'BB',
                    'name'=>'Barbados',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>20,
                    'code'=>'BY',
                    'name'=>'Belarus',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>21,
                    'code'=>'BE',
                    'name'=>'Belgium',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>22,
                    'code'=>'BZ',
                    'name'=>'Belize',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>23,
                    'code'=>'BJ',
                    'name'=>'Benin',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>24,
                    'code'=>'BM',
                    'name'=>'Bermuda',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>25,
                    'code'=>'BT',
                    'name'=>'Bhutan',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>26,
                    'code'=>'BO',
                    'name'=>'Bolivia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>27,
                    'code'=>'BA',
                    'name'=>'Bosnia and Herzegovina',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>28,
                    'code'=>'BW',
                    'name'=>'Botswana',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>29,
                    'code'=>'BV',
                    'name'=>'Bouvet Island',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>30,
                    'code'=>'BR',
                    'name'=>'Brazil',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>31,
                    'code'=>'IO',
                    'name'=>'British Indian Ocean Territory',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>32,
                    'code'=>'BN',
                    'name'=>'Brunei',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>33,
                    'code'=>'BG',
                    'name'=>'Bulgaria',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>34,
                    'code'=>'BF',
                    'name'=>'Burkina Faso',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>35,
                    'code'=>'BI',
                    'name'=>'Burundi',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>36,
                    'code'=>'KH',
                    'name'=>'Cambodia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>37,
                    'code'=>'CM',
                    'name'=>'Cameroon',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>38,
                    'code'=>'CA',
                    'name'=>'Canada',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>39,
                    'code'=>'CV',
                    'name'=>'Cape Verde',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>40,
                    'code'=>'KY',
                    'name'=>'Cayman Islands',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>41,
                    'code'=>'CF',
                    'name'=>'Central African Republic',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>42,
                    'code'=>'TD',
                    'name'=>'Chad',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>43,
                    'code'=>'CL',
                    'name'=>'Chile',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>44,
                    'code'=>'CN',
                    'name'=>'China',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>45,
                    'code'=>'CX',
                    'name'=>'Christmas Island',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>46,
                    'code'=>'CC',
                    'name'=>'Cocos (Keeling) Islands',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>47,
                    'code'=>'CO',
                    'name'=>'Colombia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>48,
                    'code'=>'KM',
                    'name'=>'Comoros',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>49,
                    'code'=>'CG',
                    'name'=>'Republic Of The Congo',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>50,
                    'code'=>'CD',
                    'name'=>'Democratic Republic Of The Congo',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>51,
                    'code'=>'CK',
                    'name'=>'Cook Islands',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>52,
                    'code'=>'CR',
                    'name'=>'Costa Rica',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>53,
                    'code'=>'CI',
                    'name'=>'Cote D Ivoire (Ivory Coast)',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>54,
                    'code'=>'HR',
                    'name'=>'Croatia (Hrvatska)',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>55,
                    'code'=>'CU',
                    'name'=>'Cuba',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>56,
                    'code'=>'CY',
                    'name'=>'Cyprus',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>57,
                    'code'=>'CZ',
                    'name'=>'Czech Republic',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>58,
                    'code'=>'DK',
                    'name'=>'Denmark',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>59,
                    'code'=>'DJ',
                    'name'=>'Djibouti',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>60,
                    'code'=>'DM',
                    'name'=>'Dominica',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>61,
                    'code'=>'DO',
                    'name'=>'Dominican Republic',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>62,
                    'code'=>'TP',
                    'name'=>'East Timor',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>63,
                    'code'=>'EC',
                    'name'=>'Ecuador',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>64,
                    'code'=>'EG',
                    'name'=>'Egypt',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>65,
                    'code'=>'SV',
                    'name'=>'El Salvador',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>66,
                    'code'=>'GQ',
                    'name'=>'Equatorial Guinea',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>67,
                    'code'=>'ER',
                    'name'=>'Eritrea',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>68,
                    'code'=>'EE',
                    'name'=>'Estonia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>69,
                    'code'=>'ET',
                    'name'=>'Ethiopia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>70,
                    'code'=>'XA',
                    'name'=>'External Territories of Australia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>71,
                    'code'=>'FK',
                    'name'=>'Falkland Islands',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>72,
                    'code'=>'FO',
                    'name'=>'Faroe Islands',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>73,
                    'code'=>'FJ',
                    'name'=>'Fiji Islands',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>74,
                    'code'=>'FI',
                    'name'=>'Finland',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>75,
                    'code'=>'FR',
                    'name'=>'France',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>76,
                    'code'=>'GF',
                    'name'=>'French Guiana',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>77,
                    'code'=>'PF',
                    'name'=>'French Polynesia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>78,
                    'code'=>'TF',
                    'name'=>'French Southern Territories',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>79,
                    'code'=>'GA',
                    'name'=>'Gabon',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>80,
                    'code'=>'GM',
                    'name'=>'Gambia The',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>81,
                    'code'=>'GE',
                    'name'=>'Georgia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>82,
                    'code'=>'DE',
                    'name'=>'Germany',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>83,
                    'code'=>'GH',
                    'name'=>'Ghana',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>84,
                    'code'=>'GI',
                    'name'=>'Gibraltar',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>85,
                    'code'=>'GR',
                    'name'=>'Greece',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>86,
                    'code'=>'GL',
                    'name'=>'Greenland',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>87,
                    'code'=>'GD',
                    'name'=>'Grenada',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>88,
                    'code'=>'GP',
                    'name'=>'Guadeloupe',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>89,
                    'code'=>'GU',
                    'name'=>'Guam',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>90,
                    'code'=>'GT',
                    'name'=>'Guatemala',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,

                ],
                [
                    'id'=>91,
                    'code'=>'XU',
                    'name'=>'Guernsey and Alderney',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>92,
                    'code'=>'GN',
                    'name'=>'Guinea',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>93,
                    'code'=>'GW',
                    'name'=>'Guinea-Bissau',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,

                ],
                [
                    'id'=>94,
                    'code'=>'GY',
                    'name'=>'Guyana',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>95,
                    'code'=>'HT',
                    'name'=>'Haiti',
                    'hasState'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>96,
                    'code'=>'HM',
                    'name'=>'Heard and McDonald Islands',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>97,
                    'code'=>'HN',
                    'name'=>'Honduras',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>98,
                    'code'=>'HK',
                    'name'=>'Hong Kong S.A.R.',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>99,
                    'code'=>'HU',
                    'name'=>'Hungary',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>100,
                    'code'=>'IS',
                    'name'=>'Iceland',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>101,
                    'code'=>'IN',
                    'name'=>'India',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>102,
                    'code'=>'id',
                    'name'=>'Indonesia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>103,
                    'code'=>'IR',
                    'name'=>'Iran',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>104,
                    'code'=>'IQ',
                    'name'=>'Iraq',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>105,
                    'code'=>'IE',
                    'name'=>'Ireland',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>106,
                    'code'=>'IL',
                    'name'=>'Israel',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>107,
                    'code'=>'IT',
                    'name'=>'Italy',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>108,
                    'code'=>'JM',
                    'name'=>'Jamaica',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>109,
                    'code'=>'JP',
                    'name'=>'Japan',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>110,
                    'code'=>'XJ',
                    'name'=>'Jersey',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>111,
                    'code'=>'JO',
                    'name'=>'Jordan',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>112,
                    'code'=>'KZ',
                    'name'=>'Kazakhstan',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>113,
                    'code'=>'KE',
                    'name'=>'Kenya',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>114,
                    'code'=>'KI',
                    'name'=>'Kiribati',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>115,
                    'code'=>'KP',
                    'name'=>'Korea North',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>116,
                    'code'=>'KR',
                    'name'=>'Korea South',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>117,
                    'code'=>'KW',
                    'name'=>'Kuwait',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>118,
                    'code'=>'KG',
                    'name'=>'Kyrgyzstan',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>119,
                    'code'=>'LA',
                    'name'=>'Laos',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>120,
                    'code'=>'LV',
                    'name'=>'Latvia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>121,
                    'code'=>'LB',
                    'name'=>'Lebanon',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>122,
                    'code'=>'LS',
                    'name'=>'Lesotho',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>123,
                    'code'=>'LR',
                    'name'=>'Liberia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>124,
                    'code'=>'LY',
                    'name'=>'Libya',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>125,
                    'code'=>'LI',
                    'name'=>'Liechtenstein',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>126,
                    'code'=>'LT',
                    'name'=>'Lithuania',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>127,
                    'code'=>'LU',
                    'name'=>'Luxembourg',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>128,
                    'code'=>'MO',
                    'name'=>'Macau S.A.R.',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>129,
                    'code'=>'MK',
                    'name'=>'Macedonia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>130,
                    'code'=>'MG',
                    'name'=>'Madagascar',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>131,
                    'code'=>'MW',
                    'name'=>'Malawi',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>132,
                    'code'=>'MY',
                    'name'=>'Malaysia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>133,
                    'code'=>'MV',
                    'name'=>'Maldives',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>134,
                    'code'=>'ML',
                    'name'=>'Mali',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>135,
                    'code'=>'MT',
                    'name'=>'Malta',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,

                ],
                [
                    'id'=>136,
                    'code'=>'XM',
                    'name'=>'Man (Isle of)',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>137,
                    'code'=>'MH',
                    'name'=>'Marshall Islands',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>138,
                    'code'=>'MQ',
                    'name'=>'Martinique',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>139,
                    'code'=>'MR',
                    'name'=>'Mauritania',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>140,
                    'code'=>'MU',
                    'name'=>'Mauritius',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>141,
                    'code'=>'YT',
                    'name'=>'Mayotte',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>142,
                    'code'=>'MX',
                    'name'=>'Mexico',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>143,
                    'code'=>'FM',
                    'name'=>'Micronesia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>144,
                    'code'=>'MD',
                    'name'=>'Moldova',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>145,
                    'code'=>'MC',
                    'name'=>'Monaco',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>146,
                    'code'=>'MN',
                    'name'=>'Mongolia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>147,
                    'code'=>'MS',
                    'name'=>'Montserrat',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>148,
                    'code'=>'MA',
                    'name'=>'Morocco',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>149,
                    'code'=>'MZ',
                    'name'=>'Mozambique',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>150,
                    'code'=>'MM',
                    'name'=>'Myanmar',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>151,
                    'code'=>'NA',
                    'name'=>'Namibia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>152,
                    'code'=>'NR',
                    'name'=>'Nauru',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>153,
                    'code'=>'NP',
                    'name'=>'Nepal',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>154,
                    'code'=>'AN',
                    'name'=>'Netherlands Antilles',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>155,
                    'code'=>'NL',
                    'name'=>'Netherlands The',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>156,
                    'code'=>'NC',
                    'name'=>'New Caledonia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>157,
                    'code'=>'NZ',
                    'name'=>'New Zealand',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>158,
                    'code'=>'NI',
                    'name'=>'Nicaragua',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>159,
                    'code'=>'NE',
                    'name'=>'Niger',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>160,
                    'code'=>'NG',
                    'name'=>'Nigeria',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>161,
                    'code'=>'NU',
                    'name'=>'Niue',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>162,
                    'code'=>'NF',
                    'name'=>'Norfolk Island',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>163,
                    'code'=>'MP',
                    'name'=>'Northern Mariana Islands',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>164,
                    'code'=>'NO',
                    'name'=>'Norway',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>165,
                    'code'=>'OM',
                    'name'=>'Oman',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>166,
                    'code'=>'PK',
                    'name'=>'Pakistan',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>167,
                    'code'=>'PW',
                    'name'=>'Palau',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>168,
                    'code'=>'PS',
                    'name'=>'Palestinian Territory Occupied',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>169,
                    'code'=>'PA',
                    'name'=>'Panama',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>170,
                    'code'=>'PG',
                    'name'=>'Papua new Guinea',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>171,
                    'code'=>'PY',
                    'name'=>'Paraguay',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>172,
                    'code'=>'PE',
                    'name'=>'Peru',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>173,
                    'code'=>'PH',
                    'name'=>'Philippines',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>174,
                    'code'=>'PN',
                    'name'=>'Pitcairn Island',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>175,
                    'code'=>'PL',
                    'name'=>'Poland',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>176,
                    'code'=>'PT',
                    'name'=>'Portugal',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>177,
                    'code'=>'PR',
                    'name'=>'Puerto Rico',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>178,
                    'code'=>'QA',
                    'name'=>'Qatar',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>179,
                    'code'=>'RE',
                    'name'=>'Reunion',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>180,
                    'code'=>'RO',
                    'name'=>'Romania',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>181,
                    'code'=>'RU',
                    'name'=>'Russia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>182,
                    'code'=>'RW',
                    'name'=>'Rwanda',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>183,
                    'code'=>'SH',
                    'name'=>'Saint Helena',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>184,
                    'code'=>'KN',
                    'name'=>'Saint Kitts And Nevis',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>185,
                    'code'=>'LC',
                    'name'=>'Saint Lucia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>186,
                    'code'=>'PM',
                    'name'=>'Saint Pierre and Miquelon',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>187,
                    'code'=>'VC',
                    'name'=>'Saint Vincent And The Grenadines',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>188,
                    'code'=>'WS',
                    'name'=>'Samoa',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>189,
                    'code'=>'SM',
                    'name'=>'San Marino',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>190,
                    'code'=>'ST',
                    'name'=>'Sao Tome and Principe',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>191,
                    'code'=>'SA',
                    'name'=>'Saudi Arabia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>192,
                    'code'=>'SN',
                    'name'=>'Senegal',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>193,
                    'code'=>'RS',
                    'name'=>'Serbia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>194,
                    'code'=>'SC',
                    'name'=>'Seychelles',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>195,
                    'code'=>'SL',
                    'name'=>'Sierra Leone',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>196,
                    'code'=>'SG',
                    'name'=>'Singapore',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>197,
                    'code'=>'SK',
                    'name'=>'Slovakia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>198,
                    'code'=>'SI',
                    'name'=>'Slovenia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>199,
                    'code'=>'XG',
                    'name'=>'Smaller Territories of the UK',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>200,
                    'code'=>'SB',
                    'name'=>'Solomon Islands',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>201,
                    'code'=>'SO',
                    'name'=>'Somalia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>202,
                    'code'=>'ZA',
                    'name'=>'South Africa',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>203,
                    'code'=>'GS',
                    'name'=>'South Georgia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>204,
                    'code'=>'SS',
                    'name'=>'South Sudan',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>205,
                    'code'=>'ES',
                    'name'=>'Spain',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>206,
                    'code'=>'LK',
                    'name'=>'Sri Lanka',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>207,
                    'code'=>'SD',
                    'name'=>'Sudan',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>208,
                    'code'=>'SR',
                    'name'=>'Suriname',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>209,
                    'code'=>'SJ',
                    'name'=>'Svalbard And Jan Mayen Islands',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>210,
                    'code'=>'SZ',
                    'name'=>'Swaziland',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>211,
                    'code'=>'SE',
                    'name'=>'Sweden',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>212,
                    'code'=>'CH',
                    'name'=>'Switzerland',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>213,
                    'code'=>'SY',
                    'name'=>'Syria',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>214,
                    'code'=>'TW',
                    'name'=>'Taiwan',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>215,
                    'code'=>'TJ',
                    'name'=>'Tajikistan',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>216,
                    'code'=>'TZ',
                    'name'=>'Tanzania',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>217,
                    'code'=>'TH',
                    'name'=>'Thailand',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>218,
                    'code'=>'TG',
                    'name'=>'Togo',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>219,
                    'code'=>'TK',
                    'name'=>'Tokelau',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>220,
                    'code'=>'TO',
                    'name'=>'Tonga',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>221,
                    'code'=>'TT',
                    'name'=>'Trinidad And Tobago',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>222,
                    'code'=>'TN',
                    'name'=>'Tunisia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>223,
                    'code'=>'TR',
                    'name'=>'Turkey',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>224,
                    'code'=>'TM',
                    'name'=>'Turkmenistan',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>225,
                    'code'=>'TC',
                    'name'=>'Turks And Caicos Islands',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>226,
                    'code'=>'TV',
                    'name'=>'Tuvalu',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>227,
                    'code'=>'UG',
                    'name'=>'Uganda',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>228,
                    'code'=>'UA',
                    'name'=>'Ukraine',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>229,
                    'code'=>'AE',
                    'name'=>'United Arab Emirates',
                    'hasState'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>230,
                    'code'=>'GB',
                    'name'=>'United Kingdom',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>231,
                    'code'=>'US',
                    'name'=>'United States',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>232,
                    'code'=>'UM',
                    'name'=>'United States Minor Outlying Islands',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>233,
                    'code'=>'UY',
                    'name'=>'Uruguay',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>234,
                    'code'=>'UZ',
                    'name'=>'Uzbekistan',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>235,
                    'code'=>'VU',
                    'name'=>'Vanuatu',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>236,
                    'code'=>'VA',
                    'name'=>'Vatican City State (Holy See)',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>237,
                    'code'=>'VE',
                    'name'=>'Venezuela',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>238,
                    'code'=>'VN',
                    'name'=>'Vietnam',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>239,
                    'code'=>'VG',
                    'name'=>'Virgin Islands (British)',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>240,
                    'code'=>'VI',
                    'name'=>'Virgin Islands (US)',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>241,
                    'code'=>'WF',
                    'name'=>'Wallis And Futuna Islands',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>242,
                    'code'=>'EH',
                    'name'=>'Western Sahara',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>243,
                    'code'=>'YE',
                    'name'=>'Yemen',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>244,
                    'code'=>'YU',
                    'name'=>'Yugoslavia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>245,
                    'code'=>'ZM',
                    'name'=>'Zambia',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],
                [
                    'id'=>246,
                    'code'=>'ZW',
                    'name'=>'Zimbabwe',
                    'hasRegion'=>1,
                    'created_by' => 1,
                    'updated_by' => 1,
                ],

            ];
            Country::insert($countries);



}
}
